@extends('layouts.head')
@section('content')
   
    <table>
        <tr>
            <td>
                Dubbelfris
            </td>
        </tr>
        @foreach ($bier as $biertje)
            <tr>
                <td>
                    {{$biertje->name}}
                </td>
                <td>
                    {{$biertje->brewer}}
                </td>
                <td>
                    {{$biertje->type}}
                </td>
                <td>
                    {{$biertje->yeast}}
                </td>
                <td>
                    {{$biertje->perc}}
                </td>
                <td>
                    {{$biertje->purchase_price}}
                </td>
                <td>
                    {{$biertje->like_count}}
                </td>
            </tr>
        @endforeach
    </table>
@endsection